name: Deploy Spring Boot to EC2 via CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Checkout source code
        uses: actions/checkout@v2

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APP_YML }}" > src/main/resources/application.yml

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🛠 Build Spring Boot Project
        run: ./gradlew clean build -x test

      - name: ✅ Make scripts executable
        run: chmod +x scripts/*.sh

      - name: 📦 Create deployment package
        run: |
          mkdir -p codedeploy-package
          cp -r appspec.yml scripts/ build/libs/*.jar codedeploy-package/
          cd codedeploy-package
          zip -r deployment.zip .

      - name: ☁️ Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl private
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: ./codedeploy-package
          DEST_DIR: code-deploy-artifacts

      - name: 🚀 Trigger AWS CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name codedeploy-web-3tier-BE \
            --deployment-group-name DG-springboot-BE \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=code-deploy-artifacts/deployment.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}